language: python
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==2.4.4"
   - DRP="rest-pandas==0.2.1"
  matrix:
   - DJANGO="django==1.6.8"
   - DJANGO="django==1.7.1"
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install requests
 - pip install $DJANGO
 - pip install $DRF
 - pip install $DRP
script:
 - python setup.py test
