language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="https://github.com/tomchristie/django-rest-framework/archive/master.zip"
   - NKEY="https://github.com/wq/django-natural-keys/archive/master.zip"
  matrix:
   - DJANGO="django==1.8.15"
   - DJANGO="django==1.9.10"
   - DJANGO="django==1.10.2"
   - DJANGO="django==1.10.2" LINT=1
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF
 - pip install $NKEY
 - pip install flake8
script:
 - ./runtests.sh
