language: python
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==3.1.1"
   - DRP="rest-pandas==0.3.1"
   - MATPLOTLIB="matplotlib>=1.4"
  matrix:
   - DJANGO="django==1.7.7"
   - DJANGO="django==1.8"
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $DRP
 - pip install $MATPLOTLIB
script:
 - python setup.py test
