language: python
python:
 - "2.7"
env:
 - DJANGO="django==1.6" DRF="https://github.com/sheppard/django-rest-framework/archive/generic-dj16.zip"
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
script:
 - python setup.py test
services:
 - redis-server
