language: python
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==2.4.2"
  matrix:
   - DJANGO="django==1.6.7" DJANGO_SETTINGS_MODULE="tests.settings"
   - DJANGO="django==1.6.7" DJANGO_SETTINGS_MODULE="tests.swap_settings"
   - DJANGO="django==1.7"   DJANGO_SETTINGS_MODULE="tests.settings"
   - DJANGO="django==1.7"   DJANGO_SETTINGS_MODULE="tests.swap_settings"
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
script:
 - python setup.py test
services:
 - redis-server
