language: python
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==2.4.2"
   - DJANGO="django==1.6.5"
  matrix:
   - DJANGO_SETTINGS_MODULE="tests.settings"
   - DJANGO_SETTINGS_MODULE="tests.swap_settings"
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
script:
 - sleep 10 # Give redis some more time to start up?
 - python setup.py test
services:
 - redis-server
