language: python
python:
 - "2.7"
env:
 - DJANGO="django==1.6" DRF="djangorestframework==2.3.9"
before_script:
 - sudo apt-get install postgresql-9.1-postgis-2.1
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
script:
 - python setup.py test
services:
 - redis-server
