language: python
python:
 - "2.7"
env:
 - DJANGO="django==1.6" DRF="djangorestframework==2.3.14" WQIO=git+https://github.com/wq/wq.io
 - DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/" DRF="djangorestframework==2.3.14" WQIO=git+https://github.com/wq/wq.io
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $WQIO
script:
 - python setup.py test
services:
 - redis-server
