language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.5.3"
  matrix:
   - DJANGO="django==1.8.16"
   - DJANGO="django==1.9.11"
   - DJANGO="django==1.10.3"
   - DJANGO="django==1.10.3" LINT=1
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF
 - pip install flake8
script:
 - ./runtests.sh
